config/routes.rb
Rails.application.routes.draw do

  get 'bands/new'
  get 'password_resets/new'
  get 'password_resets/edit'
  root 'static_pages#home'

  get '/signup', to: 'users#new'
  post '/signup',  to: 'users#create'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get 'bands/custom_search', to: 'bands#custom_search'

  #devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}







  #get 'users/:id/become_leader' => 'users#become_leader', as: become_leader

  resources :users #do
    #collection do
     # patch 'become_leader'
    #end
  #end







  resources :password_resets#,     only: [:new, :create, :edit, :update]
  resources :bands
  resources :places
  # get 'users/new'
  # get 'static_pages/help'
  # get 'static_pages/about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord

    #before_save { email.downcase! }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

    #before_create :create_activation_digest

    #devise :database_authenticatable, :registerable,
    #    :recoverable, :rememberable, :trackable, :validatable,
    #    :omniauthable, :omniauth_providers => [:facebook]

    has_one :band

    devise :rememberable, :omniauthable, omniauth_providers: [:google_oauth2]

    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
    validates :name,  presence: true, uniqueness: true, length: { maximum: 35 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email, presence: true, length: {maximum: 255}, format: { with: VALID_EMAIL_REGEX }

    attr_accessor :remember_token, :activation_token, :reset_token

  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest,  User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end


    def send_password_reset_email
        UserMailer.password_reset(self).deliver_now
    end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
        if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
            user.email = data["email"] if user.email.blank?
        end
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def facebook
        # You need to implement the method below in your model (e.g. app/models/user.rb)
        @user = User.from_omniauth(request.env["omniauth.auth"])
        if @user.persisted?
            sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
            set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
        else
            session["devise.facebook_data"] = request.env["omniauth.auth"]
            redirect_to new_user_registration_url
        end
    end

    def failure
        redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to MyBand!"
      redirect_to @user
    else
      render 'users/new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def index
    @users = User.all
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end







  #def become_leader
  #  (User.find(params[:id])).update_attribute(:leader, true)
  #end







  private

  def user_params
    #params.require(:user).permit(:name, :email, :password, :password_confirmation)
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :role, :location)
  end

end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :location %>
      <%= f.text_field :location, class: 'form-control' %>

      <%= f.label :role %>
      <%= f.select :role, ['none', 'singer', 'guitarist', 'drummer', 'bassist', 'keyboardist']%>

      <%= f.label :birth_date %>
      <%= date_select :user, :birth_date %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">change</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<style>
</style>
</head>
<body>
<% provide(:title, 'All users') %>
<h1>All users</h1>

<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= gravatar_for user%>
      <hr>
      <h2>
        <%= link_to user.name, user %>
      </h2>
      <% if current_user.try(:admin?) && !current_user?(user) %>
        | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
      <% end %>
      <% if user.location != nil && user.location != "" %>
        <iframe
            width="300"
            height="275"
            frameborder="0" style="border:0"
            src="https://www.google.com/maps/embed/v1/place?key=AIzaSyAc-JjwiFdQ5Pxtsd2f-oRCHdugaLgAzEc&q=<%= user.location %>" allowfullscreen>
        </iframe>
      <% end %>
    </li>
  <% end %>
</ul>
</body>

app/views/users/new.html.erb
<!--<h1>MyBand</h1>-->

<h2>Sign Up</h2>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %> <br/>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %> <br/>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %> <br/>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %> <br/>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
    <hr/>

    <!--<label> Have a facebook account? </label>-->
    <%# link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %>
    <%# link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path %>

    <label> Have a google account? </label>
    <%= link_to "Sign up with Google", user_google_oauth2_omniauth_authorize_path, id:'oauth' %>
  </div>
</div>

app/views/users/show.html.erb
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<style>
body {
  margin: 0;
  font-family: "Lato", sans-serif;
}

.sidebar {
  margin: 0;
  padding: 0;
  width: 200px;
  background-color: #f1f1f1;
  position: fixed;
  height: 100%;
  overflow: auto;
}

.sidebar a {
  display: block;
  color: black;
  padding: 16px;
  text-decoration: none;
}

.sidebar a.active {
  background-color: #4CAF50;
  color: white;
}

.sidebar a:hover:not(.active) {
  background-color: #555;
  color: white;
}

h3 {
    display: block;
    font-size: 1.17em;
    margin-top: 1em;
    margin-bottom: 1em;
    margin-left: 0;
    margin-right: 0;
    font-weight: normal;
}

h4 {
    display: block;
    font-size: 1.17em;
    margin-top: 1em;
    margin-bottom: 1em;
    margin-left: 0;
    margin-right: 0;
    font-weight: normal;
}

div.content {
  margin-left: 200px;
  padding: 1px 16px;
  height: 1000px;
}

@media screen and (max-width: 700px) {
  .sidebar {
    width: 100%;
    height: auto;
    position: relative;
  }
  .sidebar a {float: left;}
  div.content {margin-left: 0;}
}

@media screen and (max-width: 400px) {
  .sidebar a {
    text-align: center;
    float: none;
  }
}
</style>
</head>
<body>

<div class="sidebar">
    <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
        <% if current_user.try(:leader?) %>
            <h4>
                leader user
            </h4>
        <% else %>
            <h4>
                ordinary user
            </h4>
        <% end %>
        <% if @user.role == nil %>
            Please edit your role
        <% else %>
            <%= @user.role %>
        <% end %>
        <br/>
        <% if @user.location == nil %>
            Please edit your location
        <% else %>
            <%= @user.location %>
        <% end %>
    </h1>
    <h2>
        <% if logged_in? && (@user==current_user)%>
            <%# link_to 'Update profile information', edit_user_path(current_user) %>
            <%= link_to 'Update profile information', edit_user_path(@user) %>
        <% end %>
    </h2>
    <h3>
        <% if (logged_in? && (@user==current_user))||current_user.admin==true %>
            <%= link_to "Delete profile", @user, method: :delete, data: { confirm: "You sure?" } %>
        <% end %>
    </h3>
</div>

<div class="content">
    <% provide(:title, @user.name) %>
    <div class="row">
    <aside class="col-md-4">
        <section class="user_info">
        <h2>
            <%# button_to "Player search", 'http://localhost:3000/users', method: :get %>
            <%# button_to "Band search", 'http://localhost:3000/bands', method: :get %>
            <%# button_to "Custom search"%>
            <!--<img width="600" src="https://maps.googleapis.com/maps/api/staticmap?center=Albany,+NY&zoom=13&scale=1&size=600x300&maptype=roadmap&key=AIzaSyAc0rh3T8nZJ9SCEQDYJnfR8HPsZL9Z38M&format=png&visual_refresh=true"
            alt="Google Map of Albany, NY">-->
            <!--<img width="600" src="https://www.google.com/maps/embed/v1/place?key=AIzaSyAc-JjwiFdQ5Pxtsd2f-oRCHdugaLgAzEc&q=piazza Bologna" alt="Google Map of Albany, NY" >-->

            <br/>



            <% if (logged_in? && (@user==current_user))%>
                <% if @user.leader == false%>
                    <%# link_to 'Become a leader!', {:controller => "users", :action => "become_leader", :id => @user.id} %>
                    <%# link_to 'Become a leader!', {:controller => "users", :action => "become_leader"} %>
                    <%# link_to "Become a leader", become_leader_path(@user.id)%>

                    <span> "Do you want to create your own band?" </span>
                    <%= link_to "Become a leader", 'http://localhost:3000/bands/new' %>
                    <%# link_to "Want to create another band?", 'http://localhost:3000/bands/new' %>
                <% end %>

            <% end %>



            <br/>
            <br/>

            <!--<iframe
                width="600"
                height="450"
                frameborder="0" style="border:0"
                src="https://www.google.com/maps/embed/v1/place?key=AIzaSyAc-JjwiFdQ5Pxtsd2f-oRCHdugaLgAzEc&q=Space+Needle,Seattle+WA"
                    allowfullscreen>
            </iframe>-->
            <% if @user.location == nil %>
                <h2> Please edit your location <h2>
            <% else %>
                <iframe
                    width="600"
                    height="450"
                    frameborder="0" style="border:0"
                    src="https://www.google.com/maps/embed/v1/place?key=AIzaSyAc-JjwiFdQ5Pxtsd2f-oRCHdugaLgAzEc&q=<%= @user.location %>" allowfullscreen>
                </iframe>
            <% end %>

        </h2>
        </section>
    </aside>
    </div>
</div>

</body>
</html>