config/routes.rb
Rails.application.routes.draw do

  get 'bands/new'
  get 'password_resets/new'
  get 'password_resets/edit'
  root 'static_pages#home'

  get '/signup', to: 'users#new'
  post '/signup',  to: 'users#create'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get 'bands/custom_search', to: 'bands#custom_search'

  #devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}







  #get 'users/:id/become_leader' => 'users#become_leader', as: become_leader

  resources :users #do
    #collection do
     # patch 'become_leader'
    #end
  #end







  resources :password_resets#,     only: [:new, :create, :edit, :update]
  resources :bands
  resources :places
  # get 'users/new'
  # get 'static_pages/help'
  # get 'static_pages/about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/band.rb
class Band < ApplicationRecord
  belongs_to :user
  has_one :active_relationships, class_name:  "Relationship",
                                  foreign_key: "groupLocation",
                                  dependent:   :destroy

  validates :name,  presence: true, uniqueness: true, length: { maximum: 35 }
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def new
    @band = Band.new
  end

  def show
    @band = Band.find(params[:id])
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      #log_in @band
      flash[:success] = "Band successfully created!"
      #redirect_to @user
      redirect_to @band
      current_user.update_attribute(:leader, true)
    else
      flash[:info] = "Band name isn't valid"
      render 'bands/new'
    end
  end

  def edit
    @band = Band.find(params[:id])
  end

  def update
    @band = Band.find(params[:id])
    if @band.update_attributes(band_params)
      flash[:success] = "Band information updated"
      redirect_to @band
    else
      render 'edit'
    end
  end

  def custom_search
    render 'bands/custom_search'
  end

  def index
    @bands = Band.all
  end

  def destroy
    Band.find(params[:id]).destroy
    flash[:success] = "Band deleted"
    redirect_to bands_url
    current_user.update_attribute(:leader, false)
  end

  private

  def band_params
    params.require(:band).permit(:name, :location, :open, :user_id)
  end
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/views/bands/custom_search.html.erb
<% provide(:title, "Custom Search") %>
<h1>Custom Search</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:band, url: 'bands/custom_search') do |f| %>

      <label>Max Distance:</label>
      <select>
        <option value="5">5</option>
        <option value="10">10</option>
        <option value="20">20</option>
        <option value="50">50</option>
        <option value="100">100</option>
      </select>

      <label>Number of Members:</label>
      <select>
        <option value="1">1</option>
        <option value="2">2</option>
        <option value="3">3</option>
        <option value="4">4</option>
        <option value="5">5</option>
      </select>

      <%= f.submit "Band Search", class: "btn btn-primary" %>
    <% end %>

    <hr>

    <%= form_for(:band, url: 'bands/custom_search') do |f| %>

      <label>Max Distance:</label>
      <select>
        <option value="5">5</option>
        <option value="10">10</option>
        <option value="20">20</option>
        <option value="50">50</option>
        <option value="100">100</option>
      </select>

      <label>Role:</label>
      <select>
        <option value="singer">singer</option>
        <option value="guitarist">guitarist</option>
        <option value=drummer">drummer</option>
        <option value="bassist">bassist</option>
        <option value="keyboardist">keyboardist</option>
      </select>

      <%= f.submit "Player Search", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/bands/edit.html.erb
<% provide(:title, "Edit band") %>
<h1>Update your band information</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@band) do |f| %>
      <%# render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :location %>
      <%= f.text_field :location, class: 'form-control' %>

      <%= f.label "Looking for other members?" %>
      <%= f.check_box :open, {checked: true, checked_value: "yes", unchecked_value: "No"}  %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

 </div>
</div>

app/views/bands/index.html.erb
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<style>
</style>
</head>
<body>
<% provide(:title, 'All bands') %>
<h1>All bands</h1>

<ul class="bands">
  <% @bands.each do |band| %>
    <li>
      <h2>
        <%= link_to band.name, band %>
      </h2>
      <% if current_user.try(:admin?)%>
        | <%= link_to "delete", band, method: :delete,
                                  data: { confirm: "You sure?" } %>
      <% end %>
      <% if band.location != nil && band.location != "" %>
        <iframe
            width="300"
            height="275"
            frameborder="0" style="border:0"
            src="https://www.google.com/maps/embed/v1/place?key=AIzaSyAc-JjwiFdQ5Pxtsd2f-oRCHdugaLgAzEc&q=<%= band.location %>" allowfullscreen>
        </iframe>
      <% end %>
    </li>
  <% end %>
</ul>
</body>

app/views/bands/new.html.erb
<h1>MyBand</h1>
<h1 align=center>Create your band</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@band, url: bands_path) do |f| %>
      <%# render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %> <br/>

      <%= f.label :location %>
      <%= f.text_field :location, class: 'form-control' %> <br/>

      <!--<#%= f.label :open, class: "checkbox inline" do %>
        <#%= f.check_box :open %>
        <#span>Looking for other members?</span>
      <#% end %>-->






      <%= f.hidden_field 'user_id', :value => current_user.id %>






      <%= f.label "Looking for other members?" %>
      <%= f.check_box :open, {checked: true, checked_value: "yes", unchecked_value: "No"}  %>

      <%= f.submit "Create my band", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/bands/show.html.erb
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>






<!--<% content_for(:sidebar) do %>
	<%= render :partial => "layouts/sidebar" %>
<% end %>

<div class="wrapper">

    <!-- Sidebar -->
    <nav id="sidebar">
        <!--<% provide(:title, @band.name) %>-->
        <h1>
        </h1>
    </nav>

    <!-- Page Content -->
    <div id="content">
        <span> Your band: </span>
        <%= @band.name %>
        <br/>
        <br/>
        <span> Other members: </span>
        <%= @band.member_2.name if @band.member_2 %>
        <%= @band.member_3.name if @band.member_3 %>
        <%= @band.member_4.name if @band.member_4 %>
        <%= @band.member_5.name if @band.member_5 %>
        <br/>
        <br/>
        <span> Location: </span>
        <%= @band.location %>
        <br/>
        <br/>
        <span> Looking for other members: </span>
        <%= @band.open ? "yes" : "no" %>
        <br/>
        <br/>
        <% if (logged_in? && (@band.user_id == current_user.id))%>
            <%= button_to "Change band info", "http://localhost:3000/bands/#{@band.id}/edit", method: :get %>
            <%# button_to "Change band info", edit_band_path(@band), method: :post %>
            <%# link_to "Change band info", edit_band_path(@band) %>

            <%# link_to 'Disband the band', '#' %>

        <% end %>

        <% if (logged_in? && (@band.user_id==current_user.id))||current_user.admin==true %>
                <%= link_to "Disband the band", @band, method: :delete, data: { confirm: "You sure?" } %>
        <% end %>
    </div>
</div>






</body>
</html>