config/routes.rb
Rails.application.routes.draw do

  get 'bands/new'
  get 'password_resets/new'
  get 'password_resets/edit'
  root 'static_pages#home'

  get '/signup', to: 'users#new'
  post '/signup',  to: 'users#create'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get 'bands/custom_search', to: 'bands#custom_search'

  #devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}







  #get 'users/:id/become_leader' => 'users#become_leader', as: become_leader

  resources :users #do
    #collection do
     # patch 'become_leader'
    #end
  #end







  resources :password_resets#,     only: [:new, :create, :edit, :update]
  resources :bands
  resources :places
  # get 'users/new'
  # get 'static_pages/help'
  # get 'static_pages/about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_sidebar.html.erb
<% if logged_in? %>
<div class="col-sm-3 col-md-2 sidebar">
	<ul class="nav nav-sidebar">
	    <li class="sidebar_overview">
            <div class="row">
                <aside class="col-md-4">
                    <section class="user_info">
                        <h1>
                            <%= gravatar_for @band.user %>
                            <%= @band.user.name %>
                        </h1>
                    </section>
                </aside>
            </div></li>
  	</ul>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body>

<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Bands", bands_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>

              <% if current_user.leader==true %>
                <% @band = Band.find_by(user_id: current_user.id) %>
                <li><%= link_to "My Band", "http://localhost:3000/bands/#{@band.id}" %></li>
              <% end %>

              <!--<li><%= link_to "Settings", '#' %></li>-->
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>